apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    io.kompose.service: chat-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
  selector:
    matchLabels:
      io.kompose.service: chat-service
  template:
    metadata:
      labels:
        io.kompose.service: chat-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: chat-service
          image: ai-helpdesk-chat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: ai-helpdesk-secret
