apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
        io.kompose.network/ai-helpdesk-app-default: "true"
    spec:
      containers:
        - name: frontend
          image: ai-helpdesk-frontend:latest
          imagePullPolicy: IfNotPresent      # <-- INSIDE CONTAINERS
          ports:
            - containerPort: 8080
      restartPolicy: Always                  # <-- MUST BE Always
