apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: frontend
          image: ai-helpdesk-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ai-helpdesk-secret
